apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio
  name: minio-svc
  namespace: minio-dev
spec:
  ports:
  - name: webconsole
    port: 9090
    protocol: TCP
    targetPort: 9090
  - name: api
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: minio
  type: ClusterIP
status:
  loadBalancer: {}